import { defineResourceMetaData } from '~base/models/resource-metadata.model';

export const UsersResourceMetadata = defineResourceMetaData({
    module: 'users',
    resource: 'users',
    softDelete: true,
    auditActions: ['create', 'update', 'delete', 'export', 'import'],
    actions: ['list', 'detail', 'create', 'update', 'delete', 'export', 'import'],
    fields: [
        {
            name: 'name',
            type: 'text',
            list: true,
            detail: true,
            create: true,
            update: true,
            search: true,
            searchOption: {
                operator: 'like',
            },
        },
        {
            name: 'username',
            type: 'text',
            list: true,
            detail: true,
            create: true,
            update: true,
            search: true,
            searchOption: {
                operator: 'like',
            },
        },
        {
            name: 'deleted',
            type: 'number',
            list: true,
            detail: true,
            create: true,
            update: true,
            search: true,
            searchOption: {
                operator: 'eq',
            },
        },
        {
            name: 'status',
            type: 'number',
            list: true,
            detail: true,
            create: true,
            update: true,
            search: true,
            searchOption: {
                operator: 'eq',
            },
        },
        {
            name: 'email',
            type: 'text',
            list: true,
            detail: true,
            create: true,
            update: true,
            search: true,
            searchOption: {
                operator: 'like',
            },
        },
        {
            name: 'phone',
            type: 'text',
            list: true,
            detail: true,
            create: true,
            update: true,
            search: true,
            searchOption: {
                operator: 'like',
            },
        },
        {
            name: 'description',
            type: 'text',
            list: true,
            detail: true,
            create: true,
            update: true,
            search: false,
            searchOption: {
                operator: 'eq',
            },
        },
        {
            name: 'address',
            type: 'text',
            list: true,
            detail: true,
            create: true,
            update: true,
            search: false,
            searchOption: {
                operator: 'eq',
            },
        },
        {
            name: 'roleId',
            type: 'relate',
            relate_select: 'name',
            list: true,
            detail: true,
            create: true,
            update: true,
            search: false,
            searchOption: {
                operator: 'eq',
            },
        },
        {
            name: 'created',
            type: 'relate',
            relate_select: 'username name email',
            list: true,
            detail: true,
            create: true,
            update: true,
            search: true,
            searchOption: {
                operator: 'eq',
            },
        },
        {
            name: 'createdAt',
            type: 'datetime',
            list: true,
            detail: true,
            create: true,
            update: true,
            search: true,
            searchOption: {
                mapFilters: {
                    start: 'startDate',
                    end: 'endDate',
                },
                operator: 'between',
            },
        },
    ],
});
